version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config:/etc/other
    links:
      - server
      - web
  redis:
    image: redis:latest
    container_name: redis
    ports: 
      - 6379:6379
    volumes: 
      - ~/data/db:/data/db
  mysql:
    image: mysql:latest
    container_name: mysql
    ports: 
      - 33306:33306
    volumes: 
      - ~/data/db:/data/db
  server:
    build: ./dulele-server
    container_name: server
    restart: always
    ports:
      - 8008:8008
    external_links:
      - "mysql:mysql"
    volumes:
      - ./server/uploads:/server/uploads
  client:
    build: ./dulele-client
    container_name: client
    restart: always
    ports:
      - 8010:8010
    external_links:
      - "server:server"
      - "mysql:mysql"
  admin:
    build: ./dulele-admin
    container_name: admin
    restart: always
    ports:
      - 8009:8009
    external_links:
      - "server:server"
      - "mysql:mysql"